### ISSUE TITLE
Number Always Returns As 0

### ISSUE THREAD

**Issue by sdevine815** [GilgusMaximus/yt-subscription-count-scraper#2]
Hello, I have everything installed properly. I have Axios and the yt-subscription-count-scraper installed. Whenever I run my code, it always returns a 0. Any ideas why?

**Comment by GilgusMaximus** [comment]
Hi, thanks a lot for pointing this out. I'm quite busy at the moment and completely forgot to update this package's string matching logic to the new page layout.

I just releases a new version at npm, so you should be ready to go.
I'll close the issue. But if something doesn't work, then let me know :)
